### ISSUE TITLE
Its COM port is not showing after flashing

### ISSUE THREAD

**Issue by duraga** [serginator/Cardputer-Mouse-Jiggler#2]
Its COM port is not showing after flashing this app from m5burner. COM port of this device gets detected for a blink time when I reset it by pressing and releasing the reset button (long holding of reset button does not work)

**Comment by serginator** [comment]
Hey! You should maintain G0 button and then press reset button to enter flash mode, it's not due to my app 😓 
Anyway, I would suggest to flash `M5Launcher`, then download to SD card the firms that you want to try and install them, or install them directly through OTA ;)
